service: hono-lambda-dynamodb

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  environment:
    AWS_ACCESS_KEY_ID: local
    AWS_SECRET_ACCESS_KEY: local
    AWS_DEFAULT_REGION: ap-northeast-1
    DYNAMODB_ENDPOINT: http://dynamodb:8000

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    format: esm
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude:
      - aws-sdk
      - "@aws-sdk/*"
    platform: "node"
    target: "node20"
    outputWorkFolder: "dist"
    format: esm
    external:
      - "@aws-sdk/*"
