AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        AWS_ACCESS_KEY_ID: local
        AWS_SECRET_ACCESS_KEY: local
        AWS_DEFAULT_REGION: ap-northeast-1
        DYNAMODB_ENDPOINT: http://dynamodb:8000
  Api:
    OpenApiVersion: '2.0'

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: hono-lambda-dynamodb:latest
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: nodejs20.x-v1

Parameters:
  Stage:
    Type: String
    Default: dev

Metadata:
  AWS::SAM::Cli:
    DockerNetwork: bridge

