version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - SERVER_HOST=0.0.0.0
      - TABLE_NAME=Test
    networks:
      - dev-network
    working_dir: /workspace
    ports:
      - "3000:3000"

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

